[summary]
name = "rdlp"
date = "v2023-12-12"
version = "v0.0.1"
author = "@bayuncao"
license = "MIT"

[rules]

[rules.switch]
enable = [1, 3, 5]
disable = [2, 4, 6]


[[rules.item]]
id = 1
name = "item1"
category = "PHONE"
desc = "item1"
level = 4

detect.reg = ["detect.reg1", "detect.reg2", "detect.reg3"]
detect.list = [ "detect.list1", "detect.list2", "detect.list3"]

filter.reg = [ "filter.reg1", "filter.reg2", "filter.reg3"]
filter.list = [ "filter.list1", "filter.list2", "filter.list3"]

verify.reg = [ "verify.reg1", "verify.reg2", "verify.reg3"]
verify.list = [ "verify.list1", "verify.list2", "verify.list3"]

[[rules.item]]
id = 2
name = "item2"
category = "PHONE"
desc = "item2"
level = 4

detect.reg = ["detect.reg1", "detect.reg2", "detect.reg3"]
detect.list = [ "detect.list1", "detect.list2", "detect.list3"]

filter.reg = [ "filter.reg1", "filter.reg2", "filter.reg3"]
filter.list = [ "filter.list1", "filter.list2", "filter.list3"]

verify.reg = [ "verify.reg1", "verify.reg2", "verify.reg3"]
verify.list = [ "verify.list1", "verify.list2", "verify.list3"]

