[project]
name = "rdlp"
date = "v2023-12-12"
version = "v0.0.1"

[output]
enable = [1, 3, 5]
disable = [2, 4, 6]

[rules]

[rules.detect]



[ruls.dict]

[ruls.regex]



[[items]]
id = 1
name = "item1"
[[items]]
id = 1
name = "item1"
[[items]]
id = 1
name = "item1"
[[items]]
id = 1
name = "item1"
[[items]]
id = 1
name = "item1"
[[items]]
id = 1
name = "item1"
