[summary]
name = "rdlp"
date = "v2023-12-12"
version = "v0.0.1"
author = "@bayuncao"
license = "MIT"

[rules]

[rules.switch]
enable = [1, 3, 5]
disable = [2, 4, 6]


[[rules.item]]
id = 1
name = "item1"
[[rules.item]]
id = 1
name = "item1"
[[rules.item]]
id = 1
name = "item1"
[[rules.item]]
id = 1
name = "item1"
[[rules.item]]
id = 1
name = "item1"
[[rules.item]]
id = 1
name = "item1"
